
# This file merges asset predictions generated by passing through arrays of 
# surface reflectance measurements from Landsat Satellites through Yeh et al.
# model, and data on large scale land acquisitions from the Land Matrix. 



# ----------------------------- ENVIRONMENT ----------------------------


rm(list = ls())
setwd("~/Projects/Dissertation/agro-welfare")

library(dplyr)
library(tidyr)
library(readr)
library(forcats)
library(zoo)



# ------------------- MERGE DATASETS ----------------------

# Load Data
asset_predictions <- read_csv('data/intermediate/asset_predictions.csv')
lsla <- readRDS('data/intermediate/lsla.RData')
institutions <- read_csv('data/raw/country_indicators.csv')
country_to_code <- read_csv('data/intermediate/country_to_code.csv')

# Merge Asset Predictions and Land Acquisions 
mdta <- inner_join(asset_predictions, lsla, by='deal_id')

# Add country codes to master data
mdta <- left_join(mdta, country_to_code, by='country')

# Rename years to year
mdta <- mdta %>%
  rename(year = years)

# Pivot Institutions Data to be tidy
institutions <- institutions %>% 
  filter(Indicator %in% c("Property rights score", "Business freedom score", 
                          "Investment freedom score", "Government Integrity score"))

institutions <- pivot_longer(institutions, cols = `1995`:`2021`, 
                             names_to="year", values_to="score")
institutions <- pivot_wider(institutions, id_cols = c(`Country ISO3`, `year`), 
                            names_from=`Indicator`, values_from=`score`)
institutions$year <- as.numeric(institutions$year)

# Infer Missing Values via Linear Interpolation
institutions <- institutions %>% 
  filter(`Country ISO3` %in% country_to_code$country_code) %>%
  group_by(`Country ISO3`) %>%
  mutate(property_rights = na.approx(`Property rights score`, na.rm=FALSE),
         business_freedom = na.approx(`Business freedom score`, na.rm=FALSE), 
         investment_freedom = na.approx(`Investment freedom score`, na.rm=FALSE),
         government_integrity = na.approx(`Government Integrity score`, na.rm=FALSE)) %>%
  rename(country_code = `Country ISO3`) %>%
  ungroup()


# Merge Institutions Data into Master Data
mdta <- left_join(mdta, institutions, by=c("country_code", "year"))




# ---------------- CONSTRUCT ADDITIONAL VARIABLES ---------------------


# Construct Indicator Variables for Deal Signed, Site Active, Site Closed
mdta$signed <- as_factor(as.integer(mdta$year >= mdta$year_signed))
mdta$operational <- as_factor(as.integer(mdta$year >= mdta$year_operational))
mdta$abandoned <- as_factor(as.integer(mdta$year >= mdta$year_abandoned))


# Coerce Variables to Factor
mdta$year_fe <- as_factor(mdta$year)
mdta$level_fe <- as_factor(mdta$level)
mdta$country <- as_factor(mdta$country)
mdta$deal_id <- as_factor(mdta$deal_id)


# Create Period Dummies
mdta$pre_2000 <- as_factor(ifelse(mdta$year < 2000, 1, 0))
mdta$post_2003 <- as_factor(ifelse(mdta$year >= 2003, 1, 0))


# Create Dummies for Below Median Property Rights & Institutions
mdta$low_property_rights <- ifelse(mdta$property_rights < 30, 1, 0)
mdta$low_government_integrity <- ifelse(mdta$government_integrity < 25, 1, 0)


# Create Lagged Values of Assets
mdta <- mdta %>% 
  group_by(deal_id, tile_id) %>% 
  mutate(assets_lag_1 = lag(assets, n = 1, order_by = year), 
         assets_lag_2 = lag(assets, n = 2, order_by = year), 
         assets_lag_3 = lag(assets, n = 3, order_by = year),
         assets_lead_1 = lead(assets, n = 1, order_by = year),
         signed_lag_1 = lag(signed, n = 1, order_by = year),
         signed_lag_2 = lag(signed, n = 2, order_by = year), 
         signed_lag_3 = lag(signed, n = 3, order_by = year),
         signed_lead_1 = lead(signed, n = 1, order_by = year),
         signed_lead_2 = lead(signed, n = 2, order_by = year), 
         signed_lead_3 = lead(signed, n = 3, order_by = year),
         operational_lag_1 = lag(operational, n = 1, order_by = year),
         operational_lag_2 = lag(operational, n = 2, order_by = year), 
         operational_lag_3 = lag(operational, n = 3, order_by = year),
         operational_lead_1 = lead(operational, n = 1, order_by = year), 
         operational_lead_2 = lead(operational, n = 2, order_by = year),
         operational_lead_3 = lead(operational, n = 3, order_by = year)) %>%
  ungroup()


# Calculate Difference in Assets Since Previous Period
mdta$diff_lag <- mdta$assets - mdta$assets_lag_1
mdta$diff_lead <- mdta$assets - mdta$assets_lead_1


# Construct Years Since Signed/Active/Closed Variables
mdta$since_signed <- mdta$year - mdta$year_signed
mdta$since_operational <- mdta$year - mdta$year_operational
mdta$since_abandoned <- mdta$year - mdta$year_abandoned


# Create lag and lead dummies for the event study model
mdta$es_lag2_signed <- ifelse(mdta$since_signed == -2, 1, 0)
mdta$es_lag3_signed <- ifelse(mdta$since_signed == -3, 1, 0)
mdta$es_lagplus4_signed <- ifelse(mdta$since_signed < -3, 1, 0)

mdta$es_lead0_signed <- ifelse(mdta$since_signed == 0, 1, 0)
mdta$es_lead1_signed <- ifelse(mdta$since_signed == 1, 1, 0)
mdta$es_lead2_signed <- ifelse(mdta$since_signed == 2, 1, 0)
mdta$es_lead3_signed <- ifelse(mdta$since_signed == 3, 1, 0)
mdta$es_leadplus4_signed <- ifelse(mdta$since_signed > 3, 1, 0)

mdta$es_lag2_operational <- ifelse(mdta$since_operational == -2, 1, 0)
mdta$es_lag3_operational <- ifelse(mdta$since_operational == -3, 1, 0)
mdta$es_lagplus4_operational <- ifelse(mdta$since_operational < -3, 1, 0)

mdta$es_lead0_operational <- ifelse(mdta$since_operational == 0, 1, 0)
mdta$es_lead1_operational <- ifelse(mdta$since_operational == 1, 1, 0)
mdta$es_lead2_operational <- ifelse(mdta$since_operational == 2, 1, 0)
mdta$es_lead3_operational <- ifelse(mdta$since_operational == 3, 1, 0)
mdta$es_leadplus4_operational <- ifelse(mdta$since_operational > 3, 1, 0)




# ------------ IDENTIFY AND REMOVE UNUSUAL OBSERVATIONS --------------


# Preserve copy of data for visualization before modifications
unfiltered_data <- mdta


# Identify observations where assets changed by more than 1.0 between adjacent periods.
outliers <- unfiltered_data %>%
  filter((diff_lag < -1 | diff_lag > 1 | diff_lead < -1 | diff_lead > 1))


# Remove all tiles for which the asset predictions changed by more than 1, and winsorize
mdta <- unfiltered_data %>%
  filter(!((diff_lag < -1 | diff_lag > 1) & !is.na(diff_lag)) | 
           !((diff_lead < -1 | diff_lead > 1) & !is.na(diff_lead))) %>%  # Remove asset changes < 1
  filter(assets > -1.874129 & assets < 1.452251)  # Remove the top and bottom 0.05%





# ------------------- VALIDATE AND SAVE ------------------------------

# Write datasets
write_rds(unfiltered_data, 'data/robustness/unfiltered_data.RData')
write_rds(outliers, 'data/robustness/outliers.RData')
write_rds(mdta, 'data/mdta.RData')

