
# This file merges asset predictions generated by passing through arrays of 
# surface reflectance measurements from Landsat Satellites through Yeh et al.
# model, and data on large scale land acquisitions from the Land Matrix. 


# It also creates an additional dataset named 'robust' which removes outliers 
# which have much higher than expected changes in asset wealth, or which have 
# asset wealth of 3.13315. 



# ----------------------------- ENVIRONMENT ----------------------------
rm(list = ls())
setwd("~/Projects/Dissertation/agro-welfare")

library(dplyr)
library(readr)
library(forcats)
library(assertr)



# ------------------- MERGE DATASETS ----------------------

# Load Data
asset_predictions <- read_csv('data/asset_predictions.csv')
lsla <- readRDS('data/intermediate/lsla.RData')

# Merge Asset Predictions and Land Aquisions 
mdta <- inner_join(asset_predictions, lsla, by='deal_id')



# ---------------- CONSTRUCT ADDITIONAL VARIABLES ---------------------


# Construct Indicator Variables for Deal Signed, Site Active, Site Closed
mdta$signed <- as_factor(as.integer(mdta$year >= mdta$year_signed))
mdta$operational <- as_factor(as.integer(mdta$year >= mdta$year_operational))
mdta$abandoned <- as_factor(as.integer(mdta$year >= mdta$year_abandoned))


# Construct Years Since Signed/Active/Closed Variables
mdta$since_signed <- mdta$year - mdta$year_signed
mdta$since_operational <- mdta$year - mdta$year_operational
mdta$since_abandoned <- mdta$year - mdta$year_abandoned


# Construct Factor Variables
mdta$year_fe <- as_factor(mdta$year)
mdta$level_fe <- as_factor(mdta$level)
mdta$country <- as_factor(mdta$country)
mdta$deal_id <- as_factor(mdta$deal_id)


# Create Period Dummies
mdta$pre_2000 <- as_factor(ifelse(mdta$year < 2000, 1, 0))
mdta$post_2003 <- as_factor(ifelse(mdta$year >= 2003, 1, 0))


# Create Lagged Values of Assets
mdta <- mdta %>% 
  group_by(deal_id, tile_id) %>% 
  mutate(assets_lag_1 = lag(assets, n = 1, order_by = year), 
         assets_lag_2 = lag(assets, n = 2, order_by = year), 
         assets_lag_3 = lag(assets, n = 3, order_by = year),
         assets_lead_1 = lead(assets, n = 1, order_by = year),
         signed_lag_1 = lag(signed, n = 1, order_by = year),
         signed_lag_2 = lag(signed, n = 2, order_by = year), 
         signed_lag_3 = lag(signed, n = 3, order_by = year),
         signed_lead_1 = lead(signed, n = 1, order_by = year),
         signed_lead_2 = lead(signed, n = 2, order_by = year), 
         signed_lead_3 = lead(signed, n = 3, order_by = year),
         operational_lag_1 = lag(operational, n = 1, order_by = year),
         operational_lag_2 = lag(operational, n = 2, order_by = year), 
         operational_lag_3 = lag(operational, n = 3, order_by = year),
         operational_lead_1 = lead(operational, n = 1, order_by = year), 
         operational_lead_2 = lead(operational, n = 2, order_by = year),
         operational_lead_3 = lead(operational, n = 3, order_by = year)) %>%
  ungroup()


# Calculate Difference in Assets Since Previous Period
mdta$diff_lag <- mdta$assets - mdta$assets_lag_1
mdta$diff_lead <- mdta$assets - mdta$assets_lead_1




# ------------ IDENTIFY AND REMOVE UNUSUAL OBSERVATIONS --------------


# Preserve copy of data for visualization before modifications
unfiltered_data <- mdta


# Identify observations which inexplicably have assets of 3.131557375, or which 
# grew by more than 1 on the asset index scale since the subsequent period.
outliers <- mdta %>%
  filter((assets > 3.1315 & assets < 3.1316) | (diff < -1) | (diff > 1))


# Create dataset that drops all observations in the deal_id & year of an outlier
robust <- mdta %>%
  anti_join(outliers, by=c('deal_id', 'year'))


# Drop outliers from master dataset
mdta <- mdta %>%
  filter(!((diff_lag < -1) | (diff_lag > 1) | 
             (diff_lead < -1) | (diff_lead > 1))) %>%  # Remove asset changes < 1
  filter(assets > -1.874129 & assets < 1.452251)  # Remove the top and bottom 0.05%




# ------------------- VALIDATE AND SAVE ------------------------------

# Write datasets
write_rds(unfiltered_data, 'data/robustness/unfiltered_data.RData')
write_rds(outliers, 'data/robustness/outliers.RData')
write_rds(robust, 'data/robustness/robust.RData')
write_rds(mdta, 'data/mdta.RData')

