
# This file merges asset predictions generated by passing through arrays of 
# surfance reflectance measurements from Landsat Satellites through Yeh et al.
# (2020)'s model, and data on large scale land aquisitions from the Land Matrix. 


# ----------------------------- ENVIRONMENT ----------------------------
rm(list = ls())
setwd("~/Projects/Dissertation/agro-welfare")

library(dplyr)
library(readr)



# ------------------------- MERGE DATASETS ----------------------------

# Load Data
asset_predictions <- read_csv('data/asset_predictions.csv')
lsla <- readRDS('data/lsla.RData')

# TEMP SOLUTION UNTIL NEW FILE ADDED
asset_predictions <- rename(asset_predictions, year = years)

# Merge Asset Predictions and Land Aquisions 
mdta <- left_join(asset_predictions, lsla, by='deal_id')



# ---------------- CONSTRUCT ADDITIONAL VARIABLES ---------------------

# Construct Indicator Variables for Deal Signed, Site Active, Site Closed
mdta$signed <- as_factor(as.integer(mdta$year >= mdta$year_signed))
mdta$operational <- as_factor(as.integer(mdta$year >= mdta$year_operational))
mdta$abandoned <- as_factor(as.integer(mdta$year >= mdta$year_abandoned))

# Construct Years Since Signed/Active/Closed Variables
mdta$since_signed <- mdta$year - mdta$year_signed
mdta$since_operational <- mdta$year - mdta$year_operational
mdta$since_abandoned <- mdta$year - mdta$year_abandoned



# ---------------------------- SAVE -----------------------------------

# Write to RData
write_rds(mdta, 'mdta.RData')

